[2024-07-02T20:42:19.620+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T20:42:19.637+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:42:18.303456+00:00 [queued]>
[2024-07-02T20:42:19.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:42:18.303456+00:00 [queued]>
[2024-07-02T20:42:19.647+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T20:42:19.659+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Executar_Cubo> on 2024-07-02 20:42:18.303456+00:00
[2024-07-02T20:42:19.666+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=689) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-02T20:42:19.668+0000] {standard_task_runner.py:63} INFO - Started process 691 to run task
[2024-07-02T20:42:19.668+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Biancoll', 'Executar_Cubo', 'manual__2024-07-02T20:42:18.303456+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/Biancoll.py', '--cfg-path', '/tmp/tmp_4jeihqc']
[2024-07-02T20:42:19.670+0000] {standard_task_runner.py:91} INFO - Job 163: Subtask Executar_Cubo
[2024-07-02T20:42:19.717+0000] {task_command.py:426} INFO - Running <TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:42:18.303456+00:00 [running]> on host dd8042584cf8
[2024-07-02T20:42:19.792+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Biancoll' AIRFLOW_CTX_TASK_ID='Executar_Cubo' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T20:42:18.303456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T20:42:18.303456+00:00'
[2024-07-02T20:42:19.794+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T20:42:19.802+0000] {base.py:84} INFO - Using connection ID 'DataLake' for task execution.
[2024-07-02T20:42:19.808+0000] {base.py:84} INFO - Using connection ID 'Dowload' for task execution.
[2024-07-02T20:42:19.809+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T20:42:19.810+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Biancoll.py", line 8, in cubo_financeiro
    imbaud.salvar_excel()
  File "/opt/airflow/dags/plugin/Scripts/Salvar_Excel.py", line 32, in salvar_excel
    raise FileNotFoundError(f"Arquivo não encontrado: {arquivo}")
FileNotFoundError: Arquivo não encontrado: C:/Users/gabri/OneDrive/Data Analytics/03 - DataLake/Comparin/01-Imbaud/vendas.parquet
[2024-07-02T20:42:19.829+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Biancoll, task_id=Executar_Cubo, run_id=manual__2024-07-02T20:42:18.303456+00:00, execution_date=20240702T204218, start_date=20240702T204219, end_date=20240702T204219
[2024-07-02T20:42:19.839+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 163 for task Executar_Cubo (Arquivo não encontrado: C:/Users/gabri/OneDrive/Data Analytics/03 - DataLake/Comparin/01-Imbaud/vendas.parquet; 691)
[2024-07-02T20:42:19.883+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T20:42:19.898+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:42:19.903+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
