[2024-07-02T12:19:37.007+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T12:19:37.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T12:19:34.215131+00:00 [queued]>
[2024-07-02T12:19:37.047+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T12:19:34.215131+00:00 [queued]>
[2024-07-02T12:19:37.048+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T12:19:37.065+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Executar_Cubo> on 2024-07-02 12:19:34.215131+00:00
[2024-07-02T12:19:37.075+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=59) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-02T12:19:37.076+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Biancoll', 'Executar_Cubo', 'manual__2024-07-02T12:19:34.215131+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/Biancoll.py', '--cfg-path', '/tmp/tmp8ys9_05t']
[2024-07-02T12:19:37.079+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-07-02T12:19:37.079+0000] {standard_task_runner.py:91} INFO - Job 138: Subtask Executar_Cubo
[2024-07-02T12:19:37.164+0000] {task_command.py:426} INFO - Running <TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T12:19:34.215131+00:00 [running]> on host c8278d083165
[2024-07-02T12:19:37.274+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Biancoll' AIRFLOW_CTX_TASK_ID='Executar_Cubo' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T12:19:34.215131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T12:19:34.215131+00:00'
[2024-07-02T12:19:37.277+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T12:19:37.324+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T12:19:37.325+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Biancoll.py", line 8, in cubo_financeiro
    imbaud.salvar_excel()
  File "/opt/airflow/dags/Scripts/Salvar_Excel.py", line 6, in salvar_excel
    df = pd.read_parquet(r"C:\Users\gabri\OneDrive\Data Analytics\03 - DataLake\Comparin\01-Imbaud\vendas.parquet")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\gabri\\OneDrive\\Data Analytics\\03 - DataLake\\Comparin\\01-Imbaud\\vendas.parquet'
[2024-07-02T12:19:37.346+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Biancoll, task_id=Executar_Cubo, run_id=manual__2024-07-02T12:19:34.215131+00:00, execution_date=20240702T121934, start_date=20240702T121937, end_date=20240702T121937
[2024-07-02T12:19:37.360+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 138 for task Executar_Cubo ([Errno 2] No such file or directory: 'C:\\Users\\gabri\\OneDrive\\Data Analytics\\03 - DataLake\\Comparin\\01-Imbaud\\vendas.parquet'; 68)
[2024-07-02T12:19:37.375+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T12:19:37.396+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T12:19:37.398+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
