[2024-07-02T11:48:18.176+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:48:18.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:48:18.179+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:48:18.179+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:48:19.066+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:48:19.051+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:48:19.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:48:19.101+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.933 seconds
[2024-07-02T11:48:49.387+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:48:49.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:48:49.390+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:48:49.390+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:48:49.810+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:48:49.799+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:48:49.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:48:49.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.448 seconds
[2024-07-02T11:49:19.984+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:49:19.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:49:19.986+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:49:19.985+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:49:20.378+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:49:20.369+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:49:20.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:49:20.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.417 seconds
[2024-07-02T11:49:51.325+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:49:51.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:49:51.327+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:49:51.327+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:49:51.697+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:49:51.686+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:49:51.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:49:51.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.403 seconds
[2024-07-02T11:50:21.899+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:50:21.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:50:21.901+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:50:21.901+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:50:22.346+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:50:22.338+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:50:22.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:50:22.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.472 seconds
[2024-07-02T11:50:53.210+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:50:53.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:50:53.212+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:50:53.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:50:53.586+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:50:53.575+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:50:53.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:50:53.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.404 seconds
[2024-07-02T11:51:24.474+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:51:24.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:51:24.477+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:51:24.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:51:24.953+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:51:24.943+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:51:24.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:51:24.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.510 seconds
[2024-07-02T11:51:55.894+0000] {processor.py:161} INFO - Started process (PID=485) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:51:55.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:51:55.896+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:51:55.895+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:51:56.309+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:51:56.300+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:51:56.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:51:56.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.444 seconds
[2024-07-02T11:52:26.556+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:52:26.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:52:26.557+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:52:26.557+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:52:26.923+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:52:26.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:52:26.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:52:26.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.390 seconds
[2024-07-02T11:52:57.088+0000] {processor.py:161} INFO - Started process (PID=612) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:52:57.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:52:57.090+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:52:57.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:52:57.498+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:52:57.488+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:52:57.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:52:57.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.432 seconds
[2024-07-02T11:53:27.927+0000] {processor.py:161} INFO - Started process (PID=675) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:53:27.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:53:27.928+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:53:27.928+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:53:28.306+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:53:28.295+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:53:28.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:53:28.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.403 seconds
[2024-07-02T11:53:58.650+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:53:58.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:53:58.652+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:53:58.652+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:53:59.076+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:53:59.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:53:59.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:53:59.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.452 seconds
[2024-07-02T11:54:30.053+0000] {processor.py:161} INFO - Started process (PID=801) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:54:30.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:54:30.055+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:54:30.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:54:30.494+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:54:30.480+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:54:30.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:54:30.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.468 seconds
[2024-07-02T11:55:01.272+0000] {processor.py:161} INFO - Started process (PID=864) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:55:01.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:55:01.274+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:55:01.274+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:55:01.723+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:55:01.712+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:55:01.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:55:01.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.482 seconds
[2024-07-02T11:55:31.802+0000] {processor.py:161} INFO - Started process (PID=932) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:55:31.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:55:31.805+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:55:31.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:55:32.311+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:55:32.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:55:32.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:55:32.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.538 seconds
[2024-07-02T11:56:03.026+0000] {processor.py:161} INFO - Started process (PID=996) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:56:03.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:56:03.029+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:56:03.028+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:56:03.476+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:56:03.467+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:56:03.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:56:03.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.477 seconds
[2024-07-02T11:56:34.194+0000] {processor.py:161} INFO - Started process (PID=1058) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:56:34.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:56:34.196+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:56:34.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:56:34.581+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:56:34.571+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:56:34.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:56:34.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.413 seconds
[2024-07-02T11:57:04.726+0000] {processor.py:161} INFO - Started process (PID=1121) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:57:04.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:57:04.728+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:57:04.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:57:05.194+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:57:05.181+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:57:05.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:57:05.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.499 seconds
[2024-07-02T11:57:35.888+0000] {processor.py:161} INFO - Started process (PID=1184) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:57:35.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:57:35.890+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:57:35.890+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:57:36.254+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:57:36.244+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:57:36.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:57:36.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.391 seconds
[2024-07-02T11:58:06.618+0000] {processor.py:161} INFO - Started process (PID=1247) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:58:06.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:58:06.621+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:58:06.620+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:58:07.027+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:58:07.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:58:07.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:58:07.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.433 seconds
[2024-07-02T11:58:37.258+0000] {processor.py:161} INFO - Started process (PID=1310) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:58:37.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:58:37.260+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:58:37.260+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:58:37.673+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:58:37.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:58:37.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:58:37.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.446 seconds
[2024-07-02T11:59:07.908+0000] {processor.py:161} INFO - Started process (PID=1373) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:59:07.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:59:07.910+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:59:07.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:59:08.282+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:59:08.270+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:59:08.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:59:08.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.397 seconds
[2024-07-02T11:59:39.129+0000] {processor.py:161} INFO - Started process (PID=1436) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T11:59:39.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T11:59:39.131+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:59:39.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:59:39.525+0000] {logging_mixin.py:188} INFO - [2024-07-02T11:59:39.513+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T11:59:39.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T11:59:39.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.422 seconds
[2024-07-02T12:00:09.847+0000] {processor.py:161} INFO - Started process (PID=1499) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:00:09.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:00:09.848+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:00:09.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:00:10.227+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:00:10.215+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:00:10.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:00:10.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.405 seconds
[2024-07-02T12:00:41.086+0000] {processor.py:161} INFO - Started process (PID=1562) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:00:41.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:00:41.088+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:00:41.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:00:41.505+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:00:41.494+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:00:41.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:00:41.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.446 seconds
[2024-07-02T12:01:11.668+0000] {processor.py:161} INFO - Started process (PID=1625) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:01:11.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:01:11.670+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:01:11.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:01:12.077+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:01:12.067+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:01:12.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:01:12.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.437 seconds
[2024-07-02T12:01:42.865+0000] {processor.py:161} INFO - Started process (PID=1688) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:01:42.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:01:42.866+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:01:42.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:01:43.249+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:01:43.237+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:01:43.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:01:43.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.412 seconds
[2024-07-02T12:02:13.602+0000] {processor.py:161} INFO - Started process (PID=1751) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:02:13.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:02:13.604+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:02:13.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:02:13.890+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:02:13.879+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:02:13.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:02:13.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.316 seconds
[2024-07-02T12:02:44.094+0000] {processor.py:161} INFO - Started process (PID=1814) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:02:44.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:02:44.095+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:02:44.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:02:44.349+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:02:44.339+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:02:44.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:02:44.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.283 seconds
[2024-07-02T12:03:14.547+0000] {processor.py:161} INFO - Started process (PID=1877) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:03:14.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:03:14.550+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:03:14.550+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:03:14.823+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:03:14.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:03:14.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:03:14.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.306 seconds
[2024-07-02T12:03:45.632+0000] {processor.py:161} INFO - Started process (PID=1940) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:03:45.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:03:45.633+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:03:45.633+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:03:45.898+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:03:45.886+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:03:45.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:03:45.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.294 seconds
[2024-07-02T12:04:16.141+0000] {processor.py:161} INFO - Started process (PID=2003) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:04:16.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:04:16.143+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:04:16.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:04:16.407+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:04:16.394+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:04:16.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:04:16.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.292 seconds
[2024-07-02T12:04:46.476+0000] {processor.py:161} INFO - Started process (PID=2064) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:04:46.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:04:46.478+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:04:46.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:04:46.742+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:04:46.730+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:04:46.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:04:46.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.299 seconds
[2024-07-02T12:05:17.407+0000] {processor.py:161} INFO - Started process (PID=2128) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:05:17.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:05:17.408+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:05:17.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:05:17.666+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:05:17.658+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:05:17.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:05:17.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.288 seconds
[2024-07-02T12:07:41.693+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:07:41.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:07:41.699+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:07:41.699+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:07:42.267+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:07:42.260+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:07:42.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:07:42.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.602 seconds
[2024-07-02T12:08:12.686+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:08:12.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:08:12.690+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:08:12.689+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:08:13.075+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:08:13.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:08:13.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:08:13.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.415 seconds
[2024-07-02T12:08:43.760+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:08:43.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:08:43.763+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:08:43.763+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:08:44.204+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:08:44.194+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:08:44.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:08:44.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.470 seconds
[2024-07-02T12:09:14.578+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:09:14.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:09:14.581+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:09:14.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:09:14.968+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:09:14.959+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:09:14.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:09:14.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.417 seconds
[2024-07-02T12:09:45.654+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:09:45.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:09:45.657+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:09:45.657+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:09:46.069+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:09:46.058+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:09:46.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:09:46.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.440 seconds
[2024-07-02T12:10:16.202+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:10:16.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:10:16.204+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:10:16.204+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:10:16.612+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:10:16.599+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:10:16.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:10:16.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.435 seconds
[2024-07-02T12:10:47.262+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:10:47.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:10:47.265+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:10:47.264+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:10:47.679+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:10:47.667+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:10:47.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:10:47.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.442 seconds
[2024-07-02T12:11:17.813+0000] {processor.py:161} INFO - Started process (PID=479) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:11:17.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:11:17.818+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:11:17.817+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:11:18.291+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:11:18.283+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:11:18.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:11:18.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.505 seconds
[2024-07-02T12:11:48.548+0000] {processor.py:161} INFO - Started process (PID=542) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:11:48.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:11:48.552+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:11:48.551+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:11:49.266+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:11:49.254+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:11:49.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:11:49.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.753 seconds
[2024-07-02T12:12:19.858+0000] {processor.py:161} INFO - Started process (PID=605) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:12:19.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:12:19.861+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:12:19.861+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:12:20.337+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:12:20.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:12:20.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:12:20.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.509 seconds
[2024-07-02T12:12:51.306+0000] {processor.py:161} INFO - Started process (PID=668) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:12:51.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:12:51.309+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:12:51.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:12:51.767+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:12:51.755+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:12:51.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:12:51.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.488 seconds
[2024-07-02T12:13:22.481+0000] {processor.py:161} INFO - Started process (PID=731) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:13:22.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:13:22.484+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:13:22.483+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:13:22.871+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:13:22.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:13:22.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:13:22.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.418 seconds
[2024-07-02T12:13:52.983+0000] {processor.py:161} INFO - Started process (PID=794) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:13:52.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:13:52.986+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:13:52.985+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:13:53.367+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:13:53.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:13:53.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:13:53.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.408 seconds
[2024-07-02T12:14:24.287+0000] {processor.py:161} INFO - Started process (PID=857) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:14:24.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:14:24.290+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:14:24.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:14:24.772+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:14:24.758+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:14:24.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:14:24.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.513 seconds
[2024-07-02T12:14:54.890+0000] {processor.py:161} INFO - Started process (PID=919) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:14:54.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:14:54.893+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:14:54.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:14:55.271+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:14:55.260+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:14:55.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:14:55.293+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.408 seconds
[2024-07-02T12:15:25.361+0000] {processor.py:161} INFO - Started process (PID=982) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:15:25.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:15:25.364+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:15:25.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:15:25.722+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:15:25.714+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:15:25.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:15:25.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.381 seconds
[2024-07-02T12:18:49.949+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:18:49.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:18:49.953+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:18:49.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:18:51.047+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:18:51.037+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:18:51.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:18:51.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 1.136 seconds
[2024-07-02T12:19:21.403+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:19:21.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:19:21.408+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:19:21.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:19:21.843+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:19:21.832+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:19:21.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:19:22.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 1.198 seconds
[2024-07-02T12:19:53.159+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:19:53.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:19:53.162+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:19:53.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:19:53.634+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:19:53.621+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:19:53.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:19:53.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.503 seconds
[2024-07-02T12:20:24.076+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:20:24.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:20:24.080+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:20:24.079+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:20:24.494+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:20:24.486+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:20:24.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:20:24.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.445 seconds
[2024-07-02T12:20:54.627+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:20:54.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:20:54.631+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:20:54.631+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:20:55.056+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:20:55.046+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:20:55.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:20:55.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.452 seconds
[2024-07-02T12:21:25.585+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:21:25.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:21:25.588+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:21:25.588+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:21:25.960+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:21:25.951+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:21:25.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:21:25.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.395 seconds
[2024-07-02T12:21:56.202+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:21:56.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:21:56.205+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:21:56.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:21:56.548+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:21:56.539+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:21:56.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:21:56.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.374 seconds
[2024-07-02T12:22:27.444+0000] {processor.py:161} INFO - Started process (PID=484) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:22:27.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:22:27.448+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:22:27.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:22:27.911+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:22:27.902+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:22:27.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:22:27.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.495 seconds
[2024-07-02T12:22:58.034+0000] {processor.py:161} INFO - Started process (PID=549) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:22:58.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:22:58.040+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:22:58.040+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:22:58.694+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:22:58.682+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:22:58.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:22:58.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.693 seconds
[2024-07-02T12:23:29.094+0000] {processor.py:161} INFO - Started process (PID=615) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:23:29.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:23:29.098+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:23:29.098+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:23:29.632+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:23:29.620+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:23:29.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:23:29.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.572 seconds
[2024-07-02T12:37:13.069+0000] {processor.py:161} INFO - Started process (PID=1971) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:37:13.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:37:13.071+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:37:13.071+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:37:13.353+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:37:13.339+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:37:13.355+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:37:13.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.309 seconds
[2024-07-02T12:37:44.031+0000] {processor.py:161} INFO - Started process (PID=2034) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T12:37:44.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T12:37:44.033+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:37:44.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:37:44.322+0000] {logging_mixin.py:188} INFO - [2024-07-02T12:37:44.310+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T12:37:44.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T12:37:44.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.314 seconds
[2024-07-02T14:46:52.659+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T14:46:52.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T14:46:52.664+0000] {logging_mixin.py:188} INFO - [2024-07-02T14:46:52.663+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T14:46:52.734+0000] {logging_mixin.py:188} INFO - [2024-07-02T14:46:52.725+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T14:46:52.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T14:46:52.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.114 seconds
[2024-07-02T14:49:57.890+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T14:49:57.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T14:49:57.895+0000] {logging_mixin.py:188} INFO - [2024-07-02T14:49:57.894+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T14:49:57.936+0000] {logging_mixin.py:188} INFO - [2024-07-02T14:49:57.927+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T14:49:57.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T14:49:57.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.072 seconds
[2024-07-02T14:50:28.293+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/Implemaster.py
[2024-07-02T14:50:28.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Implemaster.py for tasks to queue
[2024-07-02T14:50:28.297+0000] {logging_mixin.py:188} INFO - [2024-07-02T14:50:28.296+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/Implemaster.py
[2024-07-02T14:50:28.340+0000] {logging_mixin.py:188} INFO - [2024-07-02T14:50:28.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/Implemaster.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Implemaster.py", line 10, in <module>
    from cod_externo import Imbaud
  File "/opt/airflow/dags/cod_externo.py", line 4, in <module>
    from utils.data import first_day
ModuleNotFoundError: No module named 'utils'
[2024-07-02T14:50:28.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Implemaster.py
[2024-07-02T14:50:28.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Implemaster.py took 0.073 seconds
